repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-PanelasGrill
repo_name: 2024.2 - Panelas_Grill


site_name: Panelas Grill

nav:
   - Home: index.md
   - Visão do produto e projeto:
      - Cenário atual do cliente e do negócio: unidade1/sessao1.md
      - Solução proposta: unidade1/sessao2.md
      - Estrategias de Engenharia de Software: unidade1/sessao3.md
      - Engenharia de Requisitos: unidade2/engenhariaRequisitos.md
      - Cronogramas e Entregas: unidade1/sessao4.md
      - Interação entre Equipe e Cliente: unidade1/sessao5.md
   - Backlog:
      - Lista de Requisitos: Backlog/sessao7.md
      - User Stories: Backlog/sessao9.md
      - Backlog do Produto: Backlog/backlog.md
      - Priorização e MVP: Backlog/mvp.md
      - DoR e DoD: Backlog/dor_dod.md
   - Estudos de caso:
      - PBB: unidade3/pbb.md
      - USM: unidade3/usm.md
      - Casos de uso: unidade4/UC.md
   - Políticas de boas práticas:
      - Políticas de Boas Práticas para Branch: Politicas/politica_branch.md
      - Políticas de Boas Práticas para Commit: Politicas/politica_commit.md
      - Políticas de Boas Práticas para Issues: Politicas/politica_issue.md
   - Lições Aprendidas: 
         - Unidade I: unidade1/licoesAprendidas.md
         - Unidade II: unidade2/LicoesAprendidasII.md
         - Unidade III: unidade3/lincoesAprendidas3.md

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: orange
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode
      primary: orange
   
extra_css:
   - css/custom.css